name: weather_app
description: A beautiful weather app using Flutter + GetX + Retrofit

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  flutter_gen: ^5.3.2
  logger: ^2.0.0
  flutter_gen_runner: ^5.3.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    # - assets/icons/
    - assets/images/
  generate: true
