name: weather_app
description: A beautiful weather app using Flutter + GetX + Retrofit

publish_to: "none" # Recommended for private packages

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Networking
  dio: ^5.4.0
  retrofit: ^4.1.0

  # Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # UI & Assets
  flutter_svg: ^2.0.7
  flutter_gen: ^5.3.2

  # Logging
  logger: ^2.0.0

  # Location Services
  geolocator: ^10.0.0
  permission_handler: ^11.3.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.6
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/icons/  # Uncomment if using icon assets

  generate: true # Required for flutter_gen


  # Optional fonts configuration (uncomment if needed)
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700
